import {ROWS,COLS,CHAINS,tileId,createGame,analyzePlacement,placeTile,buyStock,endTurn,endGame,canEnd,stockPrice,netWorth,activeChains} from './engine.mjs';

const app=document.querySelector('#app'), rules=document.querySelector('#rulesDialog'), handoff=document.querySelector('#handoffDialog');
let game=null, selected=null, sound=true, aiTimer=null;
const money=n=>`$${n.toLocaleString()}`;
const chain=id=>CHAINS.find(c=>c.id===id);
function save(){if(game)localStorage.setItem('boardroom-save',JSON.stringify(game));}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400);}
function clickSound(){if(!sound)return;const ctx=new AudioContext(),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=330;g.gain.setValueAtTime(.035,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.08);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.08);}

function renderLobby(){
  const saved=localStorage.getItem('boardroom-save');
  app.innerHTML=`<section class="hero"><div class="hero-copy"><p class="eyebrow">A game of wealth & strategy</p><h1>Build an empire.<br><em>Own the board.</em></h1><p class="lede">Place tiles. Form hotel chains. Invest before the market moves. A refined strategy classic for one to six players.</p><div class="hero-actions"><button class="button primary" id="newGame">Create game <span>→</span></button>${saved?'<button class="button secondary" id="continueGame">Continue game</button>':''}</div><div class="features"><span>◆ No account</span><span>◆ Works offline</span><span>◆ Solo or local</span></div></div><div class="hero-art"><div class="art-grid">${Array.from({length:48},(_,i)=>`<i style="--d:${i%7};--h:${20+(i*17)%65}%"></i>`).join('')}</div><div class="art-card"><small>PORTFOLIO</small><strong>$<span>12,400</span></strong><div class="spark">▁▂▂▄▃▅▇</div></div></div></section>`;
  document.querySelector('#newGame').onclick=renderSetup;
  document.querySelector('#continueGame')?.addEventListener('click',()=>{try{game=JSON.parse(saved);renderGame();}catch{localStorage.removeItem('boardroom-save');renderLobby();}});
}
function renderSetup(){
  app.innerHTML=`<section class="setup panel"><button class="back" id="back">← Back</button><p class="eyebrow">New table</p><h1>Who is playing?</h1><p>Play solo against sharp computer investors, or pass this device among friends.</p><div id="players"></div><div class="setup-actions"><button class="button secondary" id="addPlayer">+ Add player</button><button class="button primary" id="startGame">Open the market</button></div></section>`;
  const box=document.querySelector('#players');
  const add=(name,ai)=>{const i=box.children.length;if(i>=6)return;box.insertAdjacentHTML('beforeend',`<div class="player-row"><span class="player-no">${i+1}</span><input type="text" aria-label="Player ${i+1} name" maxlength="18" value="${name}"><label class="switch"><input type="checkbox" ${ai?'checked':''}><span></span> Computer</label>${i>1?'<button class="remove" aria-label="Remove player">×</button>':''}</div>`);box.lastElementChild.querySelector('.remove')?.addEventListener('click',e=>{e.currentTarget.parentElement.remove();[...box.children].forEach((r,j)=>r.querySelector('.player-no').textContent=j+1);});};
  add('You',false);add('Ada',true);add('Max',true);
  document.querySelector('#addPlayer').onclick=()=>add(`Player ${box.children.length+1}`,false);
  document.querySelector('#back').onclick=renderLobby;
  document.querySelector('#startGame').onclick=()=>{const players=[...box.children].map(r=>({name:r.querySelector('input[type=text]').value,ai:r.querySelector('input[type=checkbox]').checked}));if(players.filter(p=>!p.ai).length===0)players[0].ai=false;game=createGame({players});save();renderGame(true);};
}
function hotelCards(){return CHAINS.map(c=>{const s=game.chains[c.id],price=stockPrice(s.size,c.tier);return `<button class="hotel ${s.size?'active':''}" data-buy="${c.id}" style="--hotel:${c.color}" ${game.phase!=='buy'||!s.size?'disabled':''}><span class="hotel-mark">${c.name[0]}</span><span><b>${c.name}</b><small>${s.size?`${s.size} tiles · ${money(price)}`:'Inactive'}</small></span><span class="stock-left">${s.stock}</span></button>`;}).join('');}
function renderGame(first=false){
  clearTimeout(aiTimer);const p=game.players[game.current];selected=p.hand[0]||null;
  app.innerHTML=`<section class="game-shell"><aside class="sidebar"><div><p class="eyebrow">Hotel market</p><h2>Market board</h2></div><div class="hotels">${hotelCards()}</div><div class="legend"><span><i class="safe-dot"></i> Safe at 11 tiles</span><span>25 shares each</span></div></aside><section class="table"><div class="turnbar"><div><p class="eyebrow">Turn ${game.turn}</p><h2>${p.name}${p.ai?' <span class="ai-tag">AI</span>':''}</h2></div><div class="phase"><span class="${game.phase==='place'?'on':''}">1 Place</span><i></i><span class="${game.phase==='buy'?'on':''}">2 Invest</span></div><button class="icon-button" id="menu" aria-label="Game menu">•••</button></div><div class="board-wrap"><div class="board" style="--cols:${COLS}">${Array.from({length:ROWS*COLS},(_,i)=>{const id=tileId(Math.floor(i/COLS),i%COLS),v=game.board[id],c=chain(v);return `<button class="tile ${v?'occupied':''} ${c?'chain':''}" data-tile="${id}" style="${c?`--tile:${c.color}`:''}" aria-label="Tile ${id}${v?`, ${c?.name||'unincorporated'}`:''}"><small>${id}</small>${c?`<b>${c.name[0]}</b>`:''}</button>`;}).join('')}</div></div><div class="hand-panel"><div class="hand-head"><span>Your tiles</span><small>${game.phase==='place'?'Choose a tile to place':`Buy up to ${3-game.buys} shares, or finish`}</small></div><div class="hand">${p.hand.map(id=>`<button class="hand-tile ${id===selected?'selected':''}" data-hand="${id}">${id}</button>`).join('')}</div><div class="turn-actions"><button class="button primary" id="place" ${game.phase!=='place'?'disabled':''}>Place tile</button><button class="button secondary" id="finish" ${game.phase!=='buy'?'disabled':''}>${game.buys?'Finish buying':'Pass'}</button>${canEnd(game)?'<button class="button danger" id="endGame">End game</button>':''}</div></div></section><aside class="portfolio"><div class="cash"><small>Available cash</small><strong>${money(p.cash)}</strong><span>Net worth ${money(netWorth(game,p))}</span></div><div class="players-list"><p class="eyebrow">Investors</p>${game.players.map((x,i)=>`<div class="investor ${i===game.current?'current':''}"><i>${x.name.slice(0,2).toUpperCase()}</i><span><b>${x.name}</b><small>${x.ai?'Computer':'Human'}</small></span><strong>${money(netWorth(game,x))}</strong></div>`).join('')}</div><div class="holdings"><p class="eyebrow">Your holdings</p>${CHAINS.filter(c=>p.stocks[c.id]).map(c=>`<span><i style="background:${c.color}"></i>${c.name}<b>${p.stocks[c.id]}</b></span>`).join('')||'<small>No shares yet</small>'}</div><div class="activity"><p class="eyebrow">Market wire</p>${game.log.slice(0,4).map(x=>`<p>${x}</p>`).join('')}</div></aside></section>`;
  bindGame();
  if(game.phase==='over')renderResults(); else if(p.ai)aiTimer=setTimeout(aiTurn,650); else if(first&&game.players.filter(x=>!x.ai).length>1)showHandoff();
}
function bindGame(){
  document.querySelectorAll('[data-hand]').forEach(b=>b.onclick=()=>{selected=b.dataset.hand;document.querySelectorAll('[data-hand]').forEach(x=>x.classList.toggle('selected',x===b));});
  document.querySelectorAll('[data-tile]').forEach(b=>b.onclick=()=>{if(game.players[game.current].hand.includes(b.dataset.tile)){selected=b.dataset.tile;document.querySelector('#place').click();}});
  document.querySelector('#place').onclick=()=>{if(!selected)return toast('Choose a tile from your hand.');const a=analyzePlacement(game,selected);let founded;if(a.type==='found'){const names=CHAINS.filter(c=>!game.chains[c.id].size).map(c=>c.name);const picked=prompt(`Found which hotel?\n${names.join(', ')}`,names[0]);founded=CHAINS.find(c=>c.name.toLowerCase()===picked?.toLowerCase())?.id;}const r=placeTile(game,selected,founded);if(!r.ok)return toast(r.message);clickSound();save();renderGame();};
  document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{const r=buyStock(game,b.dataset.buy);if(!r.ok)return toast(r.message);clickSound();save();renderGame();});
  document.querySelector('#finish').onclick=()=>{endTurn(game);save();renderGame();if(!game.players[game.current].ai&&game.players.filter(x=>!x.ai).length>1)showHandoff();};
  document.querySelector('#endGame')?.addEventListener('click',()=>{if(confirm('Declare the game over and liquidate every hotel?')){endGame(game);save();renderResults();}});
  document.querySelector('#menu').onclick=()=>{if(confirm('Save and return to the title screen?')){save();renderLobby();}};
}
function aiTurn(){const p=game.players[game.current];if(!p.ai)return;if(game.phase==='place'){const legal=p.hand.map(t=>({t,a:analyzePlacement(game,t)})).filter(x=>x.a.legal);const choice=legal.sort((a,b)=>(b.a.type==='merger')-(a.a.type==='merger'))[0];if(choice)placeTile(game,choice.t);else {p.hand.shift(); if(game.bag.length)p.hand.push(game.bag.pop());}save();renderGame();return;}const options=activeChains(game).map(c=>({id:c.id,price:stockPrice(game.chains[c.id].size,c.tier),size:game.chains[c.id].size})).filter(x=>game.chains[x.id].stock&&x.price<=p.cash).sort((a,b)=>b.size-a.size);if(options.length&&game.buys<3){buyStock(game,options[game.buys%options.length].id);save();renderGame();}else{endTurn(game);save();renderGame();}};
function showHandoff(){const p=game.players[game.current];document.querySelector('#handoffName').textContent=`${p.name}, it's your turn.`;handoff.showModal();}
function renderResults(){const ranked=[...game.players].sort((a,b)=>b.cash-a.cash);app.innerHTML=`<section class="results panel"><p class="eyebrow">Closing bell</p><h1>${ranked[0].name} wins</h1><p>The market has spoken. Final portfolios have been liquidated.</p><div class="podium">${ranked.map((p,i)=>`<div><span>${i+1}</span><b>${p.name}</b><strong>${money(p.cash)}</strong></div>`).join('')}</div><button class="button primary" id="again">Play again</button><button class="button secondary" id="home">Title screen</button></section>`;document.querySelector('#again').onclick=renderSetup;document.querySelector('#home').onclick=()=>{localStorage.removeItem('boardroom-save');game=null;renderLobby();};}
document.querySelector('#rulesButton').onclick=()=>rules.showModal();document.querySelector('[data-close]').onclick=()=>rules.close();document.querySelector('#soundButton').onclick=e=>{sound=!sound;e.currentTarget.textContent=sound?'♪':'×';};document.querySelector('#handoffReady').onclick=()=>handoff.close();
renderLobby();
navigator.serviceWorker?.register('./sw.js').catch(()=>{});
